modLoader = "javafml"
loaderVersion = "[37,)"
license = "MIT"
#issueTrackerURL="http://my.issue.tracker/" #optional
[[mods]]
modId = "journeymapadditions"
version = "${file.jarVersion}"
displayName = "Journeymap Additions"
authors = "mysticdrew"

description = '''
Provides Fun Additions to Journeymap
'''
[[dependencies.journeymapadditions]]
modId = "forge"
mandatory = true
versionRange = "[37.1.1,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.journeymapadditions]]
modId = "minecraft"
mandatory = true
versionRange = "[1.17.1,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.journeymapadditions]]
modId = "journeymap"
mandatory = true
versionRange = "[5.7.1,)"
ordering = "NONE"
side = "CLIENT"